name: build

on:
  push:
    branches: [ main, "REL-*"]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    env:
       MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 11
        server-id: vpro-ossrh
        server-username: SONATYPE_USERNAME
        server-password: SONATYPE_PASSWORD
        gpg-private-key: ${{ secrets.GPG_SECRET_KEY }}
        gpg-passphrase: GPG_SECRET_KEY_PASSPHRASE
        cache: maven
    - name: Build with Maven
      run: mvn -B -Pdeploy,ossrh -U deploy
      env:
        SONATYPE_USERNAME: vpro
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        GPG_SECRET_KEY_PASSPHRASE: ${{ secrets.GPG_SECRET_KEY_PASSPHRASE }}
      #continue-on-error: true
    - name: Publish to codecov
      uses: codecov/codecov-action@v3
      continue-on-error: true
      if: github.ref == 'refs/heads/main'
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2.3.0
      if: ${{ success() || failure()}}
      
