name: build

on:
  push:
    branches: [ main, "REL-*"]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      MAVEN_ARGS: '--no-transfer-progress'
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 11
        server-id: central
        server-username: CENTRAL_USERNAME
        server-password: CENTRAL_PASSWORD
        gpg-private-key: ${{ secrets.GPG_SECRET_KEY }}
        cache: maven
    - name: Build with Maven
      run: mvn -B -Pdeploy,ossrh -U deploy
      env:
        CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
        CENTRAL_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_SECRET_KEY_PASSPHRASE }}
      #continue-on-error: true
    - name: Publish to codecov
      uses: codecov/codecov-action@v4
      continue-on-error: true
      if: github.ref == 'refs/heads/main'
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: ${{ success() || failure()}}
      
