
name: build pull request

on:
  pull_request:
    branches: [ main ]
jobs:
  build:

    runs-on: ubuntu-latest
    env:
       MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 11
        cache: maven
    - name: Build with Maven
      run: mvn -B clean test
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2.3.0
      if: ${{ success() || failure()}}
    
